---
# tasks file for linux_journald_persistent
# Linux: Изменение конфига journald.conf
- name: Linux - change journald config
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: 'Storage\s*='
    line: Storage=persistent
  register: journald_result

# Linux: Рестарт службы systemd-journald
- name: Linux - restart systemd-journald  # noqa no-handler
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  when:
    - journald_result.changed
