---
# tasks file for linux_rhsm_attach

- name: Fail if both variables are set
  when:
    - linux_subscription_list is defined
    - rhsm_attach_subscription_list is defined
  ansible.builtin.fail:
    msg: "The variables 'linux_subscription_list' and 'rhsm_attach_subscription_list' are mutually exclusive. Use only 'rhsm_attach_subscription_list'"

- name: Set effective subscription list
  ansible.builtin.set_fact:
    _rhsm_attach_subscription_list: "{{ rhsm_attach_subscription_list | default(linux_subscription_list) | default('') | lower }}"

- name: Ensure subscription list is provided
  ansible.builtin.assert:
    that:
      - _rhsm_attach_subscription_list is defined
      - _rhsm_attach_subscription_list | length > 0
      - (_rhsm_attach_subscription_list is iterable) and (_rhsm_attach_subscription_list is not mapping) and (_rhsm_attach_subscription_list is not string)
    fail_msg: >
      "Provide subscription list to attach. '_rhsm_attach_subscription_list' must be set."

- name: RHSM - Check SCA mode
  ansible.builtin.command:
    argv:
      - subscription-manager
      - status
  register: __rhsm_attach_rhsm_status
  failed_when: __rhsm_attach_rhsm_status.rc not in [0, 1]
  changed_when: false

- name: RHSM - Attach subscriptions in EL without SCA
  when: rhsm_attach__sca not in __rhsm_attach_rhsm_status.stdout
  ansible.builtin.include_tasks: add_subscription_not_sca.yml
  loop: "{{ _rhsm_attach_subscription_list }}"
  loop_control:
    loop_var: _rhsm_attach_subscription
    label: _rhsm_attach_item

- name: RHSM - Attach subscriptions in EL with SCA
  when: rhsm_attach__sca in __rhsm_attach_rhsm_status.stdout
  ansible.builtin.include_tasks: add_subscription_sca.yml
  loop: "{{ _rhsm_attach_subscription_list }}"
  loop_control:
    loop_var: _rhsm_attach_subscription
    label: _rhsm_attach_item
