---
# Добавление и конфигурация tuned профиля 'ceph'

# tuned: Установка профиля 'dpc-hw', от которого зависит профиль 'ceph'
- name: "Include tasks - 'dpc-hw_profile.yml'"
  ansible.builtin.include_tasks:
    file: "dpc-hw_profile.yml"

# tuned: Создание директории для будущего кастомного профиля tuned
- name: "Tuned - Make directory for custom profile 'ceph'"
  ansible.builtin.file:
    path: "/etc/tuned/ceph"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

# tuned: Деплой кастомного профиля tuned
- name: "Tuned - Deploy custom tuned profile 'ceph'"
  throttle: 10
  timeout: 600
  ansible.builtin.copy:
    src: "ceph.conf"
    dest: "/etc/tuned/ceph/tuned.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    force: true
