---
# Добавление и конфигурация tuned профиля 'dpc-hw'

# tuned: Создание директории для будущего кастомного профиля tuned
- name: "Tuned - Make directory for custom profile 'dpc-hw'"
  ansible.builtin.file:
    path: "/etc/tuned/dpc-hw"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

# tuned: Деплой кастомного профиля tuned
- name: "Tuned - Deploy custom tuned profile 'dpc-hw'"
  throttle: 10
  timeout: 600
  ansible.builtin.copy:
    src: "dpc-hw.conf"
    dest: "/etc/tuned/dpc-hw/tuned.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    force: true
