---
# Добавление и конфигурация tuned профиля 'secure-dpc-vm'

# tuned: Установка профиля 'dpc-vm', от которого зависит профиль 'secure-dpc-vm'
- name: "Include tasks - 'dpc-vm_profile.yml'"
  ansible.builtin.include_tasks:
    file: "dpc-vm_profile.yml"

# tuned: Создание директории для будущего кастомного профиля tuned
- name: "Tuned - Make directory for custom profile 'secure-dpc-vm'"
  ansible.builtin.file:
    path: "/etc/tuned/secure-dpc-vm"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

# tuned: Деплой кастомного профиля tuned
- name: "Tuned - Deploy custom tuned profile 'secure-dpc-vm'"
  throttle: 10
  timeout: 600
  ansible.builtin.copy:
    src: "secure-dpc-vm.conf"
    dest: "/etc/tuned/secure-dpc-vm/tuned.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    force: true
