---
# Добавление и конфигурация tuned профиля 'secure-postgresql-db'

# tuned: Установка профиля 'secure-dpc-vm', от которого зависит профиль 'secure-postgresql-db'
- name: "Include tasks - 'secure-dpc-vm_profile.yml'"
  ansible.builtin.include_tasks:
    file: "secure-dpc-vm_profile.yml"

# tuned: Создание директории для будущего кастомного профиля tuned
- name: "Tuned - Make directory for custom profile 'secure-postgresql-db'"
  ansible.builtin.file:
    path: "/etc/tuned/secure-postgresql-db"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

# tuned: Деплой кастомного профиля tuned
- name: "Tuned - Deploy custom tuned profile 'secure-postgresql-db'"
  throttle: 10
  timeout: 600
  ansible.builtin.copy:
    src: "secure-postgresql-db.conf"
    dest: "/etc/tuned/secure-postgresql-db/tuned.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    force: true
